require "colorize"
require "json"
require "./ZEROINIT/Default/Filename"
require "./ZEROINIT/Default/Path"
require "./ZEROINIT/Default/InitializationSystem"
require "./ZEROINIT/ProcessResult"
require "./ZEROINIT/InitializationSystem"
require "./ZEROINIT/Unit"
